run:
  dir: /lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/inverse/loss_guidance/experiments/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
sweep:
  dir: /lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/inverse/loss_guidance/experiments/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
