run:
  dir: /lustre/groups/ml01/projects/inverse_perturbation_models/logs/neurogenesis_morphogens/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: /lustre/groups/ml01/projects/inverse_perturbation_models/logs/neurogenesis_morphogens/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}