run:
  dir: /Users/lorenzo.consoli/Work/projects/collab-goettgens/logs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: /Users/lorenzo.consoli/Work/projects/collab-goettgens/logs/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}