dataset_name: "goettgens_sfc"
h5ad_data_kwargs:
  mode: "log_transformed"
  transformation: "arcsinh"
  cofactor: 100
split_data: True
split_kwargs:
  mode: "shuffle"
  validation_size: 0.3
  n_splits: 3
  split_idx_to_return: 1
  random_state: 42
