run:
  dir: "${oc.env:REPO_ROOT}/project_folder/logs/subpop_dists/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"
sweep:
  dir: "${oc.env:REPO_ROOT}/project_folder/logs/subpop_dists/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"
