optimizer_id: null
optimizer_kwargs:
  lr: 0.0001 #defaults to 0.001
scheduler_id: null
lr_scheduler_kwargs: null
lr_scheduler_step: null
num_time_steps: 50 #defaults to 100
solver_kwargs:
  method: "euler" #or dopri5?
