num_training_steps: 100000
valid_freq: 1000
train_batch_size: 1024
validation_batch_size: 10000
state_transforms: null
grad_steps_log_interval: 100
use_class_weights: True
class_weights_obs_col: "cell_type_reannot_final"
class_weight: "balanced"
class_weights_kwargs:
  null
