fix_noise: True
num_forward_pass_per_sample: 350
regularization: null
reg_strength: 0.0
n_time_steps_forward_model: 50
solver_kwargs_forward_model:
  method: "euler"
  atol: 1e-5
  rtol: 1e-5
gamma: 1.0
estimator: "hutch-rademacher"
use_flow_map_score_estimator: False
score_estimator: "hutch-rademacher"
use_langevin: False
