N: 1000
cfg_prob_unconditional: 0
grad_steps_log_interval: 100
num_grad_accumulation_steps: 1000
num_samples_per_validation_step: null
num_training_steps: 1500000
num_treatments_to_load: null
state_transforms: null
train_batch_size: 4096
valid_freq: 100000
validation_batch_size: 16384
validation_cfg_guidance_strength: 1
