num_training_steps: 2000000
valid_freq: 100000
train_batch_size: 8192
validation_batch_size: 16384
state_transforms: null
grad_steps_log_interval: 100
num_treatments_to_load: null
num_samples_per_validation_step: null
cfg_prob_unconditional: 0.0
validation_cfg_guidance_strength: 1.0
num_grad_accumulation_steps: 500
N: 1_000
sample_groups: True
