protocol_columns: ["gm-csf_[ng_ml]", "tpo_[ng_ml]", "sr1_[nm]", "um171_[nm]", "um729_[µm]", "scf_[ng_ml]", "butyzamide_[nm]", "retinoic_acid_[µm]", "ldl_[ng_ml]", "il3_[ng_ml]", "o2_[%]", "days_of_culture"]
protocol_obs_key_added: "protocol_id"
protocol_sep: "_"
one_hot_uns_key_added: "one_hot"
protocol_obsm_key: "condition_concat"
scatter_columns: ['FSC-A :: FSC - Area', 'FSC-H :: FSC - Height', 'FSC-W :: FSC - Width', 'SSC-A :: SSC - Area', 'SSC-H :: SSC - Height', 'SSC-W :: SSC - Width',]
base_sample_rep: null
scatter_obsm_key: "X_scatter"
concat_obsm_key: "X_concat"
log1p_exp_cols: ["gm-csf_[ng_ml]", "tpo_[ng_ml]", "sr1_[nm]", "um171_[nm]", "um729_[µm]", "scf_[ng_ml]", "butyzamide_[nm]", "retinoic_acid_[µm]", "ldl_[ng_ml]", "il3_[ng_ml]", "o2_[%]", "days_of_culture"]
log21p_exp_cols: []
