# @package _global_

# default (unconditional)
defaults:
  - _self_
  - callbacks: default
  - data: condition_ra4
  - flow_matching: hpc
  - model: default
  - paths: hpc_ood_ra4
  - training: default
  - sampling: default
  - vf: default_morphogens
  - hydra: default
  - reproducibility: default
