cfg_null_condition_token: -1
conditioning_type: film
decoder_mlp_kwargs:
  hidden_dims: 512-512-512
encode_conditions: true
encode_source: false
encode_state: true
encode_time: true
n_resnet_blocks: 3
num_training_steps: 1500000
perturbation_covariates_not_pooled: null
perturbation_encoder_output_dim: 1024
perturbation_layers_after_pooling:
  activation_class: selu
  dropout_rate: 0
  final_activation_class: identity
  hidden_dims:
  - 16
  use_batchnorm: false
  use_dropout: false
perturbation_layers_before_pooling:
  feats_condition_concat_condition_concat:
    activation_class: selu
    dropout_rate: 0
    final_activation_class: identity
    hidden_dims:
    - 16
    input_dim: 12
    output_dim: 16
    use_batchnorm: false
    use_dropout: false
perturbation_pooling: mean
perturbation_pooling_kwargs: null
resnet_dropout_prob: 0
resnet_normalization: batch
source_encoder_mlp_kwargs: null
source_encoder_output_dim: 4
state_encoder_mlp_kwargs:
  hidden_dims: 512-512
state_encoder_output_dim: 256
time_encoder_mlp_kwargs:
  hidden_dims: 512-512
time_encoder_output_dim: 512
time_features_max_periods: 1000
time_features_num_freqs: 512
use_classifier_free_guidance: false
use_guidance: true
use_sinusoidal_time_features: true
use_source_as_condition: false
