dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/cell_type_classifier/${now:%Y-%m-%d}_${now:%H-%M-%S}"
h5ad_path: "${oc.env:REPO_ROOT}/project_folder/derived/loop0_annotated_500k.h5ad"
log_dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/cell_type_classifier/${now:%Y-%m-%d}_${now:%H-%M-%S}"
