dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/cell_type_classifier/${now:%Y-%m-%d}_${now:%H-%M-%S}"
h5ad_path: "${oc.env:REPO_ROOT}/project_folder/data/gdrive/ds_HID01_logicle_100k_UMAP_ann.h5ad"
log_dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/cell_type_classifier/${now:%Y-%m-%d}_${now:%H-%M-%S}"
