dump_dir: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/${now:%Y-%m-%d}_${now:%H-%M-%S}"
train_h5ad_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/data/RA_4/train_adata_flow.h5ad"
val_h5ad_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/data/RA_4/val_adata_flow.h5ad"
test_h5ad_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/data/RA_4/test_adata_flow.h5ad"
log_dir: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/logs/forward/${now:%Y-%m-%d}_${now:%H-%M-%S}"