dump_dir: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/checkpoints/cell_type_classifier_loop2/${now:%Y-%m-%d}_${now:%H-%M-%S}"
h5ad_path: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/miscellaneous_new/BloodPlus_Loop2_logicle_reannot.h5ad"
log_dir: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/logs/forward/cell_type_classifier_loop2/${now:%Y-%m-%d}_${now:%H-%M-%S}"
