dump_dir: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/checkpoints/cell_type_classifier/loop2_replicate/${now:%Y-%m-%d}_${now:%H-%M-%S}"
h5ad_path: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/loops/data/loop2/replicate/reannot/adata_500k.h5ad"
log_dir: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/logs/forward/cell_type_classifier_loop2_replicate/${now:%Y-%m-%d}_${now:%H-%M-%S}"
