dump_dir: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/prior/flow_matching/${now:%Y-%m-%d}_${now:%H-%M-%S}"
forward_model_checkpoint_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/conditional_model/2026-09-09_10-08-58/still-salad-11_FlowMatching.pkl"
log_dir: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/logs/prior/flow_matching/${now:%Y-%m-%d}_${now:%H-%M-%S}"
