dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/prior/loop_2p5_replicate"
forward_model_checkpoint_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/forward_model/loop2_5/2026-06-17_17-19-47/vague-river-4_FlowMatching.pkl"
log_dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/prior/flow_matching"
