dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/prior/loop_2_replicate"
forward_model_checkpoint_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/forward_model/loop2/2026-06-17_17-19-47/fresh-bee-21_FlowMatching.pkl"
log_dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/prior/flow_matching"
