dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/prior/loop_3_replicate"
forward_model_checkpoint_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/forward_model/loop3/2026-06-18_07-18-13/winter-sea-13_FlowMatching.pkl"
log_dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/prior/flow_matching"
