# @package _global_

defaults:
  - override /hydra/sweeper/sampler: random 
  - override /hydra/sweeper: optuna 
  
optimized_metric: all_conditions_wasserstein_distance

hydra:

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    n_jobs: 10
    
    n_trials: 30

    sampler: 
      _target_: optuna.samplers.RandomSampler

    # define hyperparameter search space
    params:

      vf.state_encoder_mlp_kwargs.hidden_dims: choice("16", " 32")

      vf.time_encoder_mlp_kwargs.hidden_dims: choice("32", "64")

      vf.decoder_mlp_kwargs.hidden_dims: choice("64", "64-64", "64-64-64")
      
      vf.resnet_normalization: choice("batch", "none")

      vf.perturbation_layers_before_pooling.repr_protocol_protocol_one_hot.hidden_dims: choice("16", "32")

      vf.perturbation_layers_before_pooling.repr_protocol_protocol_one_hot.output_dim: choice(16, 32)
      
      vf.perturbation_layers_after_pooling.hidden_dims: choice("16", "32")

      vf.perturbation_encoder_output_dim: choice(16, 32)

      vf.state_encoder_output_dim: choice(16, 32)
