target_cell_type: "MgkPro"
N: 125
num_time_steps: 500
solver_kwargs:
  method: "euler"
sde_sampling: False
query_pure_cell_types: False
mask_gradients: True
target_probs: [0.05, 0.05, 0.00, 0.00, 0.05, 0.01, 0.01, 0.05, 0.00, 0.05, 0.05, 0.00, 0.05, 0.05, 0.05, 0.05, 0.42, 0.01, 0.05]
mask: [False, False, True, True, False, False, False, False, True, False, False, True, False, False, False, False, True, False, False]
