# @package _global_

defaults:
  - override /hydra/sweeper/sampler: grid 
  - override /hydra/sweeper: optuna 
  
optimized_metric: all_conditions_wasserstein_distance

hydra:

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    # n_jobs: 16
    n_jobs: 50

    # n_trials: 16
    n_trials: 225

    sampler: 
      _target_: optuna.samplers.GridSampler

    # define hyperparameter search space
    params:
      # loss_guidance.n_time_steps_forward_model: choice(10, 50, 100)
      # run.random_seed: choice(42, 512, 1024)
      sampling.num_time_steps: choice(100, 200, 500)
      scheduler.scheduler_id: choice("constant")
      scheduler.scheduler_kwargs.lmax: choice(1.0, 3.0, 5.0, 7.0)
      sampling.mask_gradients: choice(True, False)
