perturbation_prediction_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/conditional_model/2026-07-12_17-45-26/glorious-capybara-2_FlowMatching.pkl"
ct_classifier_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/2026-07-20_20-32-49/eager-monkey-7_TargetPredictionModel.pkl"
prior_flow_path: None
dump_dir: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/inverse/loss_guidance/raw_data"
