perturbation_prediction_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/conditional_model/2026-09-09_10-08-58/still-salad-11_FlowMatching.pkl"
ct_classifier_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/2026-09-01_15-33-38/deep-wood-2_TargetPredictionModel.pkl"
prior_flow_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/prior/flow_matching/2026-09-09_21-09-10/gallant-forest-2_FlowMatching.pkl"
prior_flow_map_path:

#prior_flow_map_path: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/checkpoints/prior/flow_matching/2026-09-15_18-58-35/whole-elevator-7_FlowMap.pkl"
dump_dir: "/lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/inverse/loss_guidance"