perturbation_prediction_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/forward_model/loop3/2026-06-22_15-10-12/rich-sunset-44_FlowMatching.pkl"
ct_classifier_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/cell_type_classifier/2026-04-08_00-00-38/easy-monkey-341_TargetPredictionModel.pkl"
prior_flow_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/prior/loop3_replicate/comic-aardvark-33_FlowMatchingWithScore.pkl"
prior_flow_map_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/prior/loop3_replicate/floral-river-34_FlowMap.pkl"
dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/inverse/loss_guidance/loop3_replicate"
