perturbation_prediction_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/forward_model/loop2p5/2026-06-22_12-36-05/celestial-fire-40_FlowMatching.pkl"
ct_classifier_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/cell_type_classifier/2026-04-08_00-00-38/easy-monkey-341_TargetPredictionModel.pkl"
prior_flow_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/prior/loop_2p5_replicate/soft-brook-35_FlowMatchingWithScore.pkl"
prior_flow_map_path: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/prior/loop_2p5_replicate/ancient-grass-37_FlowMap.pkl"
dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/inverse/loss_guidance/loop2p5_replicate"
