dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/conditional_model/flow_matching/${now:%Y-%m-%d}_${now:%H-%M-%S}"
h5ad_path: "${oc.env:REPO_ROOT}/project_folder/output/loops/data/loop1/adata_full.h5ad"
log_dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/conditional_model/flow_matching/${now:%Y-%m-%d}_${now:%H-%M-%S}"
