dump_dir: "C:/Users/IliaNavosha/Projects/Output/checkpoints/conditional_model/${now:%Y-%m-%d}_${now:%H-%M-%S}"
train_h5ad_path: "C:/Users/IliaNavosha/Desktop/train_adata.h5ad"
val_h5ad_path: "C:/Users/IliaNavosha/Desktop/val_adata.h5ad"
log_dir: "C:/Users/IliaNavosha/Projects/Output/conditional_model/${now:%Y-%m-%d}_${now:%H-%M-%S}"
