dump_dir: "${oc.env:REPO_ROOT}/project_folder/output/checkpoints/forward_model/loop2p5/${now:%Y-%m-%d}_${now:%H-%M-%S}"
h5ad_path: "${oc.env:REPO_ROOT}/project_folder/output/loops/data/loop2p5/replicate/adata_full.h5ad"
log_dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/conditional_model/flow_matching/loop2_5/${now:%Y-%m-%d}_${now:%H-%M-%S}"
