# @package _global_

# default
defaults:
  - _self_
  - callbacks: "default"
  - data: "Region_default"
  - hydra: "default"
  - model: "Region_default"
  - paths: "hpc_ood_ra4"
  - reproducibility: "default"
#  - splits: "shuffle"
  - training: "default"
#  - transforms: "default"
