# @package _global_

defaults:
  - override /hydra/sweeper/sampler: random 
  - override /hydra/sweeper: optuna 
  
optimized_metric: all_conditions_wasserstein_distance

hydra:

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    n_jobs: 20
    
    n_trials: 20

    sampler: 
      _target_: optuna.samplers.RandomSampler

    # define hyperparameter search space
    params:

      vf.state_encoder_mlp_kwargs.hidden_dims: choice("32-32", "64-64")

      vf.state_encoder_output_dim: choice(16, 32)

      vf.time_encoder_output_dim: choice(16, 32)

      vf.time_encoder_mlp_kwargs.hidden_dims: choice("16-16", "32-32")

      vf.perturbation_encoder_output_dim: choice(16, 32)

      vf.decoder_mlp_kwargs.hidden_dims: choice("64-64-64", "128-128-128")

      vf.conditioning_type: choice("concatenation", "resnet", "film")
