encode_state: True
state_encoder_output_dim: 16
state_encoder_mlp_kwargs:
  hidden_dims: 256
encode_time: True
use_sinusoidal_time_features: True
time_features_num_freqs: 256
time_features_max_periods: 100
time_encoder_output_dim: 8
time_encoder_mlp_kwargs:
  hidden_dims: 256
use_guidance: True
encode_conditions: True
perturbation_encoder_output_dim: 4
perturbation_layers_before_pooling:
  repr_740-yp_[µm]_740-yp_[µm]_one_hot:
    input_dim: 1
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_mtg_[µm]_mtg_[µm]_one_hot:
    input_dim: 1
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_rhflt3l_[ng_ml]_rhflt3l_[ng_ml]_one_hot:
    input_dim: 1
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_gm-csf_[ng_ml]_gm-csf_[ng_ml]_one_hot:
    input_dim: 3
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_tpo_[ng_ml]_tpo_[ng_ml]_one_hot:
    input_dim: 5
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_sr1_[nm]_sr1_[nm]_one_hot:
    input_dim: 4
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_um171_[nm]_um171_[nm]_one_hot:
    input_dim: 6
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_um729_[µm]_um729_[µm]_one_hot:
    input_dim: 4
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_scf_[ng_ml]_scf_[ng_ml]_one_hot:
    input_dim: 3
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_butyzamide_[nm]_butyzamide_[nm]_one_hot:
    input_dim: 2
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_retinoic_acid_[µm]_retinoic_acid_[µm]_one_hot:
    # input_dim: 4
    input_dim: 3
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_ldl_[ng_ml]_ldl_[ng_ml]_one_hot:
    input_dim: 6
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_il3_[ng_ml]_il3_[ng_ml]_one_hot:
    input_dim: 5
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_o2_[%]_o2_[%]_one_hot:
    input_dim: 2
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
  repr_days_of_culture_days_of_culture_one_hot:
    input_dim: 6
    output_dim: 16
    hidden_dims: [16, ]
    use_batchnorm: False
    use_dropout: False
    dropout_rate: 0.0
    activation_class: "selu"
    final_activation_class: "identity"
perturbation_covariates_not_pooled: null
perturbation_pooling: "mean"
perturbation_pooling_kwargs: null
perturbation_layers_after_pooling:
  hidden_dims: [16, ]
  use_batchnorm: False
  use_dropout: False
  dropout_rate: 0.0
  activation_class: "selu"
  final_activation_class: "identity"
decoder_mlp_kwargs:
  hidden_dims: 256
use_source_as_condition: False
encode_source: False
source_encoder_output_dim: 4
source_encoder_mlp_kwargs: null
conditioning_type: "resnet"
n_resnet_blocks: 3
resnet_dropout_prob: 0.0
resnet_normalization: null
use_classifier_free_guidance: False
cfg_null_condition_token: -1.0
