wandb_project_name: "OOD_RA_4"
wandb_kwargs:
  entity: "i-navosha-technical-university-of-munich"
metrics: ["micro_f1_score", "micro_recall", "micro_precision", "macro_f1_score", "macro_recall", "macro_precision"]
save_model: True