# @package _global_

# default (unconditional)
defaults:
  - _self_
  - annotation: default
  - callbacks: default
  - data: ohe_protocols
  - flow_matching: hpc
  - model: default
  - paths: hpc_subset
  - split: default
  - training: debug
  - transforms: default
  - vf: default_ohe_protocols_debug
  - hydra: default
  - reproducibility: default
