h5ad_data_path: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/theis/HID01_fcs_concatenated.h5ad"
log_dir: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/log/${now:%Y-%m-%d}_${now:%H-%M-%S}"
dump_dir: "/lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/dumps/${now:%Y-%m-%d}_${now:%H-%M-%S}"