# @package _global_

# default (unconditional)
defaults:
  - _self_
  - callbacks: default
  - annotation: default
  - flow_matching: hpc
  - hydra: default
  - model: default
  - paths: hpc_full
  - reproducibility: default
  - run: default
  - training: default
  - vf: default
