run:
  dir: /lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/logs/subpop_dists/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
sweep:
  dir: /lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/logs/subpop_dists/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
