target_cell_type: "HSCs"
N: 100
num_time_steps: 100
solver_kwargs:
  method: "euler"
sde_sampling: False
query_pure_cell_types: True
mask_gradients: False
target_probs: [0.07, 0.07, 0.00, 0.00, 0.07, 0.01, 0.07, 0.07, 0.00, 0.07, 0.07, 0.00, 0.21, 0.07, 0.07, 0.07, 0.00, 0.01, 0.07]
mask: [False, False, True, True, False, False, False, False, True, False, False, True, True, False, False, False, True, False, False]
