run:
  dir: /lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/logs/forward/conditional_model/flow_matching/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
sweep:
  dir: /lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/logs/forward/conditional_model/flow_matching/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
