run:
  dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/conditional_model/flow_matching/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"
sweep:
  dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/conditional_model/flow_matching/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"
