run:
  dir: /lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/logs/forward/conditional_model/flow_matching/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
sweep:
  dir: /lustre/groups/ml01/workspace/lorenzo.consoli/projects/SFC_cambridge/output/logs/forward/conditional_model/flow_matching/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/
