run:
  dir: "C:/Users/IliaNavosha/Projects/Output/logs/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"
sweep:
  dir: "C:/Users/IliaNavosha/Projects/Output/logs/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"