scatter_columns: ["FSC - Area", "FSC - Height", "FSC - Width", "SSC - Area", "SSC - Height", "SSC - Width"]
scatter_obsm_key: "X_scatter"
channel_concat_obsm_key: "X_channel_concat"
pca_obsm_key: "X_pca"
pca_concat_obsm_key: "X_pca_concat"
standardize_repr: False
sample_rep: "X_channel_concat"
sample_rep_obsm_key: "X_repr"
repr_params_uns_key: "repr_params"
compute_channel_pcs: True
standardize_channel_feats: False
channel_feats_obsm_key: "X_channel"
channel_params_uns_key: "channel_params"
standardize_scatter_feats: True
scatter_params_uns_key: "channel_params"
