run:
  dir: /lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/logs/forward/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: /lustre/groups/ml01/workspace/ilia.navosha/projects/ood/output/logs/forward/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
