run:
  dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/cell_type_classifier_loop2/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"
sweep:
  dir: "${oc.env:REPO_ROOT}/project_folder/output/logs/forward/cell_type_classifier_loop2/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra/"
