run:
  dir: "C:/Users/IliaNavosha/Projects/Output/cell_type_classification/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra"
sweep:
  dir: "C:/Users/IliaNavosha/Projects/Output/cell_type_classification/${now:%Y-%m-%d}_${now:%H-%M-%S}/hydra"